name: Shopify Sync Live

on:
  pull_request:
    types: [ opened, reopened, synchronize]
    branches: [ main ]
permissions:
  contents: write
jobs:
  check_sync_status:
    name: Check Sync Status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli
      - name: Pull Live Theme
        env:
          SHOPIFY_FLAG_STORE: '${{ secrets.SHOPIFY_FLAG_STORE }}'
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_CLI_TTY: 0
        run: cd theme && shopify theme pull -l
      - name: Check for Updates
        id: git_check
        uses: tj-actions/verify-changed-files@v20
        with:
          files: |
            theme

      - name: Commit and Push Changes
        if: steps.git_check.outputs.files_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.verify-changed-files.outputs.changed_files }}
        run: |
          echo "Changed files: $CHANGED_FILES"
          git config --local user.name "shopify[bot]"
          git config --local user.email "<>"
          git add .
          git commit -m "Update from Live Theme"
          git push
