name: Shopify Sync Live

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  check_sync_status:
    name: Check Sync Status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli
      - name: Pull Live Theme
        env:
          SHOPIFY_FLAG_STORE: '${{ secrets.SHOPIFY_FLAG_STORE }}'
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_CLI_TTY: 0
        run: shopify theme pull -l
      - name: Check for Updates
        id: git_check
        run: |
          if [[-n $(git status -s)]]; then
            echo "::set-output name=updated::true"
          else
            echo "::set-output name=updated::false"
          fi
      - name: Commit and Push Changes
        if: steps.git_check.outputs.updated == 'true'
        run: |
          git config --local user.name "shopify[bot]"
          git add .
          git commit -m "Update from Live Theme"
          git push origin main
      - name: Check for Conflicts
        run: |
          echo "Check for conflicts manually or implement a notification here."
